on:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: smash-test
        run: |
          brew info
          brew install smashedr/keg/smash-test
          smash-test.sh

      - name: macls
        run: |
          brew info
          brew install smashedr/keg/macls
          macls
